/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_4e36197a (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/mkbcjxnoeevtkzaqcpsh/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e36197a").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_4e36197a").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e36197a").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e36197a").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_4e36197a").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_4e36197a").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const escaped = prefix.replace(/[%_]/g, (ch) => `\\${ch}`);
  const { data, error } = await supabase.from("kv_store_4e36197a").select("key, value").like("key", escaped + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Delete keys under a prefix whose value matches isExpired. The check runs in code:
// expiresAt is stored as epoch millis, and a SQL text comparison against a date
// string would match every row.
export const deleteByPrefixWhere = async (
  prefix: string,
  isExpired: (value: any) => boolean,
): Promise<number> => {
  const supabase = client();
  const escaped = prefix.replace(/[%_]/g, (ch) => `\\${ch}`);
  const { data, error } = await supabase
    .from('kv_store_4e36197a')
    .select('key, value')
    .like('key', escaped + '%');
  if (error) throw new Error(error.message);
  const keys = (data ?? []).filter((d) => isExpired(d.value)).map((d) => d.key);
  for (let i = 0; i < keys.length; i += 200) {
    await mdel(keys.slice(i, i + 200));
  }
  return keys.length;
};

// Conditional write: updates value only if the current updatedAt matches expectedUpdatedAt.
// Returns true if the row was updated (lock acquired), false if someone else wrote first.
// Only works on EXISTING keys — use set() to create new records.
export const setIfUnchanged = async (
  key: string,
  expectedUpdatedAt: string | null,
  value: any,
): Promise<boolean> => {
  const supabase = client();
  let q = supabase.from("kv_store_4e36197a").update({ value }).eq("key", key);
  q = expectedUpdatedAt === null
    ? q.is("value->>updatedAt", null)
    : q.eq("value->>updatedAt", expectedUpdatedAt);
  const { data, error } = await q.select("key");
  if (error) throw new Error(error.message);
  return (data?.length ?? 0) > 0;
};